<?php
/**
 * Created by PhpStorm.
 * User: rousl
 * Date: 08.02.2020
 * Time: 20:40
 */

namespace app\models\Airemissions;

use Yii;

class CarbonDioxide extends Airemissions
{
    public function __construct(){
        parent::__construct();
        $this->setName(Yii::t('main', 'Carbon dioxide'));
    }

    public function calcEmissionMetric()
    {
        try{
            $this->setEmissionMetric(44 / 12 *
                $this->getFuel()->carbon / 100 *
                pow(10, 6) /
                $this->getFuel()->lower_combustion_heat *
                //0.995
                0.85047 // TODO узнать почему такое число
                // это ec из формулы
            );
        }catch (\Exception $ex){
            $this->setException($ex);
            $this->setEmissionMetric(null);
        }
        return parent::calcEmissionMetric(); // TODO: Change the autogenerated stub
    }

}