<?php
/**
 * Created by PhpStorm.
 * User: rousl
 * Date: 08.02.2020
 * Time: 20:47
 */

namespace app\models\Airemissions;

use Yii;

class Methane extends Airemissions
{
    public function __construct(){
        parent::__construct();
        $this->setName(Yii::t('main', 'Methane'));
    }

    public function calcEmissionMetric()
    {
        try{
            $this->setEmissionMetric(
                $this->getFuel()->fueltype->EmissionCH4
            );
        }catch (\Exception $ex){
            $this->setException($ex);
            $this->setEmissionMetric(null);
        }
        return parent::calcEmissionMetric(); // TODO: Change the autogenerated stub
    }

}