<?php
/**
 * Created by PhpStorm.
 * User: rousl
 * Date: 08.02.2020
 * Time: 20:27
 */

namespace app\models\Airemissions;

use Yii;

class NitrogenDioxide extends Airemissions
{

    public function __construct(){
        parent::__construct();
        $this->setName(Yii::t('main', 'Nitrogen dioxide'));
    }

    public function calcEmissionMetric()
    {
        try{
            $this->setEmissionMetric(
                pow(10, 6) /
                $this->getFuel()->lower_combustion_heat *
                $this->getFuel()->nitrogen /
                100 *
                2
            );
        }catch (\Exception $ex){
            $this->setException($ex);
            $this->setEmissionMetric(null);
        }
        return parent::calcEmissionMetric(); // TODO: Change the autogenerated stub
    }

    public function calcMassSubstance()
    {
        try {
            $massSubstance = parent::calcMassSubstance();
            if (!empty($massSubstance) && !empty($this->getCatalyst())){
                $this->setMassSubstance($massSubstance *
                    (100.0 - $this->getCatalyst()->declineNitrogenDioxide) / 100.0);
            }
        }catch (\Exception $ex){
            $this->setException($ex);
            $this->setMassSubstance(null);
        }
        return $this->getMassSubstance();
    }
}