<?php
/**
 * Created by PhpStorm.
 * User: rousl
 * Date: 09.02.2020
 * Time: 19:51
 */

namespace app\models\Airemissions;

use Yii;

class SpecificVolumeDryFlueGas extends Airemissions
{
    public function __construct(){
        parent::__construct();
        $this->setName(Yii::t('main', 'Specific volume of dry flue gas'));
    }

    public function calcMassSubstance()
    {
        try{
            $Vo2 = 0.01 * (
                1.866 * $this->getFuel()->carbon +
                5.56 * $this->getFuel()->hydrogen +
                0.7 * $this->getFuel()->sulfur -
                0.7 * $this->getFuel()->oxygen
                );
            // питомий об'єм азоту у повітрі
            $Vn2air = 3.76 * $Vo2;
            // дымовые газы
            $v0fg = 0.01 * (
                    1.866 * $this->getFuel()->carbon +
                    0.7 * $this->getFuel()->sulfur +
                    0.8 * $this->getFuel()->nitrogen
                ) + $Vn2air;
            // Стандартний об'ємний вміст кисню у сухих димових газах
            // TODO не совсем понятно почему 6
            $O2st = 6;
            $v0fg = $v0fg * 21 / (21 - $O2st);
            $this->setMassSubstance( $v0fg );
        }catch (\Exception $ex){
            $this->setException($ex);
            $this->setMassSubstance(null);
        }
        return parent::getMassSubstance(); // TODO: Change the autogenerated stub
    }

}