<?php
/**
 * Created by PhpStorm.
 * User: rousl
 * Date: 08.02.2020
 * Time: 20:00
 */

namespace app\models\Airemissions;

use Yii;

class SuspendedSolids extends Airemissions
{
    private $lightAsh;
    private $massContentCombustibleSubstances;
    private $efficiencyPurification;
    private $emissionMetricSulfurOxide;

    public function __construct(){
        parent::__construct();
        $this->setName(Yii::t('main', 'Substances in the form of suspended solids'));
        $this->lightAsh = 0.0078;
        $this->massContentCombustibleSubstances = 99;
    }

    public function calcEmissionMetric()
    {
        try{
            $this->setEmissionMetric(
                pow(10, 6) /
                $this->getFuel()->lower_combustion_heat *
                $this->lightAsh *
                $this->getFuel()->ash /
                (100 - $this->massContentCombustibleSubstances) *
                (1 - $this->efficiencyPurification) +
                $this->emissionMetricSulfurOxide
            );
        }catch (\Exception $ex){
            $this->setException($ex);
            $this->setEmissionMetric(null);
        }
        return parent::calcEmissionMetric(); // TODO: Change the autogenerated stub
    }

    /**
     * @return mixed
     */
    public function getLightAsh()
    {
        return $this->lightAsh;
    }

    /**
     * @param mixed $lightAsh
     */
    public function setLightAsh($lightAsh)
    {
        $this->lightAsh = $lightAsh;
    }

    /**
     * @return mixed
     */
    public function getMassContentCombustibleSubstances()
    {
        return $this->massContentCombustibleSubstances;
    }

    /**
     * @param mixed $massContentCombustibleSubstances
     */
    public function setMassContentCombustibleSubstances($massContentCombustibleSubstances)
    {
        $this->massContentCombustibleSubstances = $massContentCombustibleSubstances;
    }

    /**
     * @return mixed
     */
    public function getEfficiencyPurification()
    {
        return $this->efficiencyPurification;
    }

    /**
     * @param mixed $efficiencyPurification
     */
    public function setEfficiencyPurification($efficiencyPurification)
    {
        $this->efficiencyPurification = $efficiencyPurification;
    }

    /**
     * @return mixed
     */
    public function getEmissionMetricSulfurOxide()
    {
        return $this->emissionMetricSulfurOxide;
    }

    /**
     * @param mixed $emissionMetricSulfurOxide
     */
    public function setEmissionMetricSulfurOxide($emissionMetricSulfurOxide)
    {
        $this->emissionMetricSulfurOxide = $emissionMetricSulfurOxide;
    }

}